### ISSUE TITLE
Download new ver 4.1.5 don't have .dll

### ISSUE THREAD

**Issue by kedaitinh12** [jpsdr/AutoYUY2#1]
It's mistake or other main meaning from you??

**Comment by jpsdr** [comment]
I just checked the .7z, the DLL are inside.

**Comment by jpsdr** [comment]
Ok... just cheked the x64, the x86 directory is a mistake.

**Comment by jpsdr** [comment]
New proper 7z uploaded.

**Comment by kedaitinh12** [comment]
Thanks
